version: "3.3"
services:
  server:
    image: alvinndungu/yolobackend:v1.0.1
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - yolo_net
    volumes:
      - yolovol:/var/lib/docker/volumes/yolovol/_data
  client:
    image: alvinndungu/yoloclient:v1.0.1
    ports:
      - "3000:3000"
    networks:
      - yolo_net
    volumes:
      - yolovol:/var/lib/docker/volumes/yolovol/_data
    depends_on:
      - server
    stdin_open: true
networks:
  yolo_net:
volumes:
  yolovol:
